# Generated by Django 6.0.3 on 2026-03-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_rename_movies_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemahall',
            old_name='seat_in_row',
            new_name='seats_in_row',
        ),
    ]
